name: Build cpp project with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

      - name: Build submodules
        run: git submodule update --init

      - name: Configure Wayland+X11 static library
        run: cmake -B build-full-static -D GLFW_BUILD_WAYLAND=ON -D GLFW_BUILD_X11=ON
      
      - name: Build Wayland+X11 static library
        run: cmake --build build-full-static --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: build-static-linux
          path: ./build-full-static/lypo_engine

        # Ajouter apres les runs de tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build submodules
        run: git submodule update --init

      - name: Configure Win32 static x64 library
        run: cmake -B build-win32-static-x64 -G "Visual Studio 17 2022" -A x64

      - name: Build Win32 static x64 library
        run: cmake --build build-win32-static-x64 --parallel
      
      - uses: actions/upload-artifact@v4
        with:
          name: build-static-windows
          path: ./build-full-static/lypo_engine.exe